version: '3.8'
services:
  accountapi:
    build:
      context: ./src/AccountApi
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
